const getFolderText = (folderIndex) => {
    switch (folderIndex) {
      case 1:
        return "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!";
      case 2:
        return "Consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!";
      case 3:
        return "Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!";
      case 4:
        return "Laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!";
      default:
        return "Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate provident velit laborum quibusdam vitae itaque, unde dicta recusandae? Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti! Numquam suscipit eum autem consequatur porro rerum iusto recusandae aliquid itaque deleniti!   Lorem ipsum dolor sit amet consectetur adipisicing elit.";
    }
  };
  
  export default getFolderText;